#!/bin/bash

#test file to get data from file as rows for now

#TMP1=./tempfile

tempCol="tempcolfile"
tempmeanlist="temporatylist"

while read myline
do
sum=0
divisor=0
echo "______________________________________"
   echo "$myline"
   for i in $myline
   do
     # echo "$i"
     sum=`expr $sum + $i`
     divisor=`expr $divisor + 1`
   done
   echo "sum: $sum"
   mean=`expr $sum / $divisor`
   echo "mean: $mean"
   echo "$mean" >> "$tempmeanlist$$"
   cat $tempmeanlist$$
done < $1

echo "finished $1"





